### ISSUE TITLE
Ask for reimplement the case “face of a boy in 3D metal”

### ISSUE THREAD

**Issue by 5RJ** [lqiang67/rectified-flow#27]
Thanks for your great code. But have you tried to get the result of edit the 3D metal flower into "face of a boy"? I've tried several pairs of start_t, end_t and eta_base，but still failed to get the result in paper. If you have succeed, could you please share the setting?
![image](https://github.com/user-attachments/assets/0f0ead8c-43bb-4bd8-8dab-661db68f58f4)

**Comment by CyberDragon93** [comment]
Hi, in my exps, I cannot reproduce the abstract style editing as well 

You can refer to this [reply](https://github.com/DarkMnDragon/rf-inversion-diffuser/issues/2#issuecomment-2482116072)

**Comment by 5RJ** [comment]
well, I adjust the prompt（"face of a boy in 3d metal."）, and get the approached result:

analytic_velocity = AnalyticGaussianVelocity(dataset=img_latent, interp=rectified_flow.interp)

editing_velocity_field = EditingVelocityFiled(
    velocity_model=flux_model,
    analytic_velocity=analytic_velocity,
    start_t=0.,
    end_t=0.25,
    eta_base=0.93,
    eta_trend='exponential_decrease',
    alpha=2.,
)

editing_rectified_flow = RectifiedFlow(
    data_shape=flux_model.dit_latent_shape,
    velocity_field=editing_velocity_field,
    interp="straight",
    device=device,
	dtype=DTYPE,
)


editing_velocity_field.start_t = 0
editing_velocity_field.end_t = 0.15
editing_velocity_field.eta_base = 0.7

stochastic_sampler = SDESampler(
    rectified_flow=editing_rectified_flow,
    time_grid=time_grid,
    num_samples=1,
    noise_scale=2.0,
)

prompt = "face of a boy in 3d metal."


x_1 = stochastic_sampler.sample_loop(seed=0, prompt=prompt, guidance_scale=3.5).trajectories[-1]


x_1_rec = flux_model.decode(x_1)
plt.figure(figsize=(2*5,5))
plt.subplot(1,2,1)
plt.imshow(img_rec)
plt.subplot(1,2,2)
plt.imshow(x_1_rec)
plt.axis("off")
plt.show()

![image](https://github.com/user-attachments/assets/e55615e2-7a23-4f85-b385-ee0bdbb980e6)

**Comment by CyberDragon93** [comment]
Cool, I think with this approach, it cannot achieve editing based on abstract semantic meanings (like generating an image in the style of "melting metal flowers"). In the end, you might get something like "a boy in 3D metal," but that’s mostly because the prompt is exactly "3d metal" and some color guidance was added early on. Alternatively, you could just use the same prompt directly (without editing velocity, i.e., $\eta = 0$) to get a pretty similar result.

**Comment by CyberDragon93** [comment]
![image](https://github.com/user-attachments/assets/6140d547-6c57-4ddc-890b-e6eafa571d6e)
Some more result
